name: Sync Google Contacts

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout mydjango-crm
      uses: actions/checkout@v4
    - name: Install uv with all available options
      uses: astral-sh/setup-uv@v7
    - name: Sync deps for Python
      run: uv sync --frozen
    - name: Run Django Management Command for contact sync
      working-directory: ./mcc
      run: uv run python manage.py sync_contacts --max-results 2
